version: "3.7"
services:
  nginx:
    container_name: regga-restapi-starter-nginx 
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${PUBLIC_PORT}:80
    restart: always
    depends_on:
      - api
  api:
    container_name: regga-restapi-starter
    build:
      dockerfile: ${DOCKER_FILE}
      context: ./api
    volumes:
      - /usr/app/node_modules
      - ./api:/usr/app
    restart: always
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    links: 
      - mongodb
    ports:
      - 5000:5000
  mongodb:
    container_name: regga-restapi-starter-mongodb
    image: mongo:jammy
    restart: always
    volumes:
      - ./mongodb/data:/data/db
      # - type: bind
      #   source: ./mongodb/data
      #   target: /data/db
